name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    on:
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:
    jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    
  uses: actions/setup-node@v1
  with:
    node-version: '10.x'
    
    
    - name: Install Dependencies
  run: npm install

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
      
      jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
        steps:
- run: npm publish
  if: github.event == 'push'

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
